# Generated by Django 5.0.6 on 2024-07-25 02:41

import django.db.models.deletion
import faq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('faq', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(default=faq.models.get_default_faq_content_type_id, on_delete=django.db.models.deletion.CASCADE, related_name='faq_comment_set', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
