# Generated by Django 4.2.13 on 2024-05-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('flat', 'Flat'), ('house', 'House'), ('boat', 'Boat'), ('land', 'Land'), ('other', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('furnished_type', models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished'), ('part_furnished', 'Part Furnished')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=4)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('garden', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('property_image', models.ImageField(upload_to='property_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
