# Generated by Django 4.2.13 on 2024-05-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='energy_efficiency_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('detached-houses', 'Detached houses'), ('semi-detached-houses', 'Semi-detached houses'), ('terraced-houses', 'Terraced houses'), ('mobile-park-homes', 'Mobile / Park homes'), ('boats', 'Boats'), ('flats-apartments', 'Flats / Apartments'), ('bungalows', 'Bungalows'), ('land', 'Land'), ('commercial-property', 'Commercial Property'), ('hmo', "HMO's")], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='real_estate.property')),
            ],
        ),
    ]
