# Generated by Django 4.2.13 on 2024-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_property_energy_efficiency_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=4),
        ),
    ]
