# Generated by Django 4.2.13 on 2024-05-27 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0007_viewingslot_viewingappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingappointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='real_estate.viewingslot'),
        ),
        migrations.AlterField(
            model_name='viewingappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewingslot',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
