# Generated by Django 4.2.13 on 2024-05-27 21:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0008_alter_viewingappointment_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewingappointment',
            old_name='booked_on',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='contact',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='message',
            field=models.TextField(default='No message'),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='preferred_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='preferred_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.property'),
        ),
        migrations.AlterField(
            model_name='viewingappointment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_estate.viewingslot'),
        ),
        migrations.AlterField(
            model_name='viewingappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
