# Generated by Django 4.2.13 on 2024-05-27 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0009_rename_booked_on_viewingappointment_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingappointment',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='real_estate.property'),
            preserve_default=False,
        ),
    ]
