# Generated by Django 4.2.13 on 2024-06-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0010_alter_viewingappointment_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingappointment',
            name='viewing_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
