# Generated by Django 4.2.13 on 2024-06-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0012_rename_status_property_publication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingappointment',
            name='agent_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
