# Generated by Django 4.2.13 on 2024-06-02 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0016_savedsearch_bathrooms_max_savedsearch_bathrooms_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymessage',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
