# Generated by Django 4.2.13 on 2024-06-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0018_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
