# Generated by Django 4.2.13 on 2024-06-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0023_alter_propertymessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('student', 'Student Accommodation')], max_length=8),
        ),
    ]
