# Generated by Django 5.0.6 on 2024-07-04 16:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0025_alter_property_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_image',
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
