# Generated by Django 5.0.6 on 2024-07-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0026_remove_property_property_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='featured_image',
            new_name='property_image',
        ),
    ]
