# Generated by Django 5.0.6 on 2024-07-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0028_alter_propertyimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_image',
        ),
    ]
