# Generated by Django 5.0.6 on 2024-07-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0030_remove_propertyalert_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('student', 'Student Accommodation'), ('land', 'Land')], max_length=8),
        ),
    ]
