# Generated by Django 5.0.6 on 2024-07-28 23:12

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0033_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
