# Generated by Django 5.0.6 on 2024-08-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0034_alter_property_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='energy_efficiency_rating',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_plan',
        ),
    ]
