# Generated by Django 5.0.6 on 2025-01-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0035_remove_property_energy_efficiency_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingappointment',
            name='viewing_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
