# Generated by Django 4.2.13 on 2024-05-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelessness_advice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomelessnessAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='HomelessSupport',
        ),
    ]
