# Generated by Django 5.0.6 on 2024-07-28 22:53

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelessness_advice', '0005_alter_post_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Homeless',
        ),
        migrations.CreateModel(
            name='HomelessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('homeless', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='homelessness_advice.homeless')),
            ],
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
