# Generated by Django 4.2.13 on 2024-05-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('detached-houses', 'Detached houses'), ('semi-detached-houses', 'Semi-detached houses'), ('terraced-houses', 'Terraced houses'), ('mobile-park-homes', 'Mobile / Park homes'), ('boats', 'Boats'), ('flats-apartments', 'Flats / Apartments'), ('bungalows', 'Bungalows'), ('land', 'Land'), ('commercial-property', 'Commercial Property'), ('hmo', "HMO's")], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('furnished_type', models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished'), ('part_furnished', 'Part Furnished')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garden', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('property_image', models.ImageField(default='default.jpg', upload_to='student_accommodation_images/')),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
                ('energy_efficiency_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
