# Generated by Django 4.2.13 on 2024-05-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_accommodation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProperty',
            new_name='StudentAccommodation',
        ),
    ]
