# Generated by Django 4.2.13 on 2024-06-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_accommodation', '0002_rename_status_studentproperty_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='student_accommodation.studentproperty')),
            ],
        ),
    ]
