# Generated by Django 4.2.13 on 2024-06-02 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_accommodation', '0003_studentpropertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproperty',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
