# Generated by Django 4.2.13 on 2024-06-25 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_accommodation', '0004_studentproperty_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='viewingslot',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accommodation.agent'),
        ),
    ]
