# Generated by Django 4.2.13 on 2024-06-25 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_accommodation', '0005_agent_alter_viewingslot_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingslot',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_agent_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
