# Generated by Django 5.0.6 on 2024-07-28 23:12

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_post_blog_blogimage_delete_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
