# Generated by Django 5.0.6 on 2024-08-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_content_type_remove_comment_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pending_approval',
            field=models.BooleanField(default=False),
        ),
    ]
