# Generated by Django 5.0.6 on 2024-08-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_pending_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='blog',
            new_name='post',
        ),
    ]
