# Generated by Django 5.0.6 on 2024-07-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='content',
            new_name='body',
        ),
    ]
