# Generated by Django 4.2.13 on 2024-07-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_guides', '0002_post_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Landlord', 'Landlord'), ('Renter', 'Renter'), ('Student', 'Student'), ('Neighbour Disputes', 'Neighbour Disputes')], default='Landlord', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
