# Generated by Django 4.2.13 on 2024-07-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_guides', '0003_post_category_alter_post_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Landlord', 'Landlord'), ('Renter', 'Renter'), ('Student', 'Student'), ('Neighbour Disputes', 'Neighbour Disputes'), ('Repairs', 'Repairs'), ('Fire Safety', 'Fire Safety'), ('Complaints', 'Complaints'), ('Eviction', 'Eviction')], default='Landlord', max_length=50),
        ),
    ]
